---
# Port to serve the website on.
port: 54321

# Paths are relative to the location of superman_server.py
datasets: datasets.yml
logfile: logs/server.log

# Login password for access to private datasets and tools.
# If not provided, the server will disable login
# and won't load any private datasets.
password: superman

# Random string for encrypting cookie data.
# If not provided, the server will generate a new secret on startup.
cookie_secret: sdfjnwp9483nzjafagq582bqd
